version: "2"
services:
  # ADOT Collector
  aws-ot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
      - AWS_REGION=us-east-1

      - AWS_PROFILE=<profile>
      - AWS_ACCESS_KEY_ID=<key id>
      - AWS_SECRET_ACCESS_KEY=<access key>
    volumes:
      - ./config-test.yaml:/etc/otel-agent-config.yaml
      - ~/.aws:/root/.aws
    ports:
      # These 3 ports are new: exposing the collector to the host machine
      - "4317:4317"
      - "55680:55680"
      - "8889:8888"

      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
